version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: khtrm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-khtrm_db}
      MYSQL_USER: ${MYSQL_USER:-khtrm_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-change_this_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
    networks:
      - khtrm-network

  # Python FastAPI Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: khtrm-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-khtrm_user}:${MYSQL_PASSWORD:-change_this_password}@mysql:3306/${MYSQL_DATABASE:-khtrm_db}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER:-khtrm_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-change_this_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-khtrm_db}
      - DEBUG=False
      - DATABASE_ECHO=False
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    networks:
      - khtrm-network

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: khtrm-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - khtrm-network

  # Nginx Reverse Proxy (опционально)
  nginx:
    image: nginx:alpine
    container_name: khtrm-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - khtrm-network

volumes:
  mysql_data:

networks:
  khtrm-network:
    driver: bridge 